projects:
  app:
    schemaPath: "../backend/src/schema.graphql"
    extensions:
      endpoints:
        default: "http://localhost:4444"
  prisma:
    schemaPath: "../backend/src/generated/prisma.graphql"
    extensions:
      prisma: prisma.yml
